apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: trigger-vision
spec:
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      #apiVersion: v1
      kind: Service
      name: vision

